### ISSUE TITLE
StudioContainerWithNestedXBlocksMixin - default css for buttons

### ISSUE THREAD

**Issue by e-kolpakov** [openedx/xblock-utils#25]
`StudioContainerWithNestedXBlocksMixin` requires descendant block to provide it's own css rules for buttons, so if it gails to do that buttons look like this:

![screen shot 2015-09-07 at 10 52 50 pm](https://cloud.githubusercontent.com/assets/945577/9727373/30b59c92-55b3-11e5-8585-4de7acdc5c3c.png)

The css rules to avoid that would likely be simple: https://github.com/open-craft/xblock-group-project-v2/blob/master/group_project_v2/public/css/group_project_edit.css#L2-L14

**Comment by feanil** [comment]
Closing old issues before archiving the repository.
